spring:
  application:
    name: backend-assignment
  datasource:
    url: jdbc:mysql://localhost:3306/ipl2
    username: root
    password: Naga@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9999

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.indium: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
